#!/usr/bin/env bash

set -euo pipefail
set -x

upstream_release_tag=v$(cat dex-github-release/version)

cd concourse-dex

source ci/scripts/common.sh

git fetch origin

create-branch-track-upstream-release "$upstream_release_tag"

list-pr-branches | while read b _; do
  git checkout $b
  git rebase $upstream_release_tag
  git push -f origin $b:$b;
done
