resource_types:
- name: slack-notifier
  type: registry-image
  source: {repository: mockersf/concourse-slack-notifier}

resources:
- name: dex-github-release
  type: github-release
  icon: &release-icon package-variant-closed
  source:
    owner: dexidp
    repository: dex
    access_token: ((concourse_github_dummy.access_token))

- name: concourse-dex
  type: git
  icon: github
  source:
    uri: git@github.com:concourse/dex.git
    branch: maintenance
    private_key: ((concourse_dex_deploy_key))

- name: concourse
  type: git
  icon: github
  source:
    uri: git@github.com:concourse/dex.git
    branch: master
    private_key: ((concourse_repo_private_key))

- name: fork-version
  type: semver
  source:
    initial_version: 0.1.0
    uri: git@github.com:concourse/dex.git
    driver: git
    branch: maintenance
    file: version
    private_key: ((concourse_dex_deploy_key))

- name: notify
  type: slack-notifier
  icon: slack
  source:
    url: ((slack_hooks.concourse-interrupt))
    username: ((basic_auth.username))
    password: ((basic_auth.password))
    concourse_url: https://ci.concourse-ci.org

jobs:
- name: update-prs
  plan:
  - in_parallel:
      - get: dex-github-release
        trigger: true
      - get: concourse-dex
      - get: concourse
      - get: concourse-dex-version
        resource: fork-version
  - task: rebase-and-push
    file: concourse-dex/ci/rebase-and-push-dex-prs.yml
    params:
      CONCOURSE_DEX_DEPLOY_KEY: ((concourse_dex_deploy_key))
  - task: create-merged-tag
    file: concourse-dex/ci/create-merged-tag.yml
    params:
      CONCOURSE_DEX_DEPLOY_KEY: ((concourse_dex_deploy_key))
    input_mapping:
      dex: concourse-dex
  - put: fork-version
    params: {bump: minor}
  on_failure: &failed-dex
    put: notify
    params:
      mode: normal
      alert_type: failed
